from django.urls import path

from app_shop import views

urlpatterns = [
    path(
        "",
        views.MainView.as_view(),
        name="main",
    ),
    path(
        "faker/",
        views.FakerView.as_view(),
        name="faker",
    ),
    path(
        "products/",
        views.ProductListView.as_view(),
        name="products",
    ),
    path(
        "product/<int:pk>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path(
        "new-collection/",
        views.NewCollectionListView.as_view(),
        name="new_collection",
    ),
    path(
        "cart/",
        views.CartView.as_view(),
        name="cart",
    ),
    path(
        "add_quantity/<int:product_id>/",
        views.add_quantity_view,
        name="add_quantity",
    ),
    path(
        "remove_quantity/<int:product_id>/",
        views.remove_quantity_view,
        name="remove_quantity",
    ),
    path(
        "add_cart/<int:product_id>/",
        views.add_to_cart_view,
        name="add_cart",
    ),
    path(
        "remove_cart/<int:product_id>/",
        views.remove_from_cart_view,
        name="remove_cart",
    ),
    path(
        "recommended/",
        views.RecommendedProductView.as_view(),
        name="recommended",
    ),
]
