# Generated by Django 3.2.9 on 2022-02-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balans',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='Баланс Пользователя'),
        ),
    ]
