# Generated by Django 3.2.9 on 2022-02-23 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Сезона')),
                ('description', models.TextField(verbose_name='Описание Сезона')),
                ('season_status', models.CharField(choices=[('new', 'Новая Коллекция'), ('recommended', 'Рекомендуемая К Покупке Коллекция'), ('default', 'Обычная Коллекция')], default='default', max_length=11, verbose_name='Статус Коллекции')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='season',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='app_shop.season', verbose_name='Сезон Продукта'),
        ),
    ]
