# Generated by Django 3.2.9 on 2022-03-01 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_shop', '0005_auto_20220227_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='cart_for_cart_product', to='app_shop.CartProduct', verbose_name='Товары в карзине'),
        ),
    ]
